Alluxio caching
apc999/presto-1 pull request #2
Opened 2020-04-22 07:34 UTC by apc999

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2020-04-22 19:53 UTC, jainxrohit requested changes

2020-04-22 19:53 UTC, jainxrohit commented on presto-hive/src/main/java/com/facebook/presto/hive/cache/HiveCachingHdfsConfiguration.java
> +                if (cacheConfig.isCachingEnabled() && cacheConfig.getCacheType() == ALLUXIO) {
Hey Bin, as we discussed yesterday, we wanted AlluxioCachingFileSystem to be independent of CachingFileSystem. We would need to create a new abstraction to route caching to either existing CachingFileSystem or AlluxioCachingFileSystem.

2020-04-22 19:53 UTC, jainxrohit commented on pom.xml
> +        <dep.airlift.version>0.190</dep.airlift.version>
My earlier changes were old. We should not be downgrading dependencies here.

2020-04-24 19:24 UTC, apc999 commented on pom.xml
> +        <dep.airlift.version>0.190</dep.airlift.version>
fixed

2020-04-28 16:49 UTC, closed without merging